### ISSUE TITLE
Fix anura-engine group permissions.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#319]
Some changes to group organization need to be made to the anura-engine group.

- [x] Jetrel needs to be made an administrator.
- [x] I need to be made an administrator.
- [x] Vultraz needs to be added to the group. (Currently, he is in a personal sub-group.)
- [x] The imgui repository needs to be made group-writable.
